# Generated by Django 2.0.6 on 2018-07-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_data',
            field=models.DateTimeField(null=True),
        ),
    ]
